# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 13:37
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoRental', '0008_auto_20181112_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='titre')),
                ('country', models.CharField(blank=True, max_length=25, null=True, verbose_name='pays')),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique_with=['title'])),
            ],
            options={
                'managed': True,
                'db_table': 'videoRental_movie_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'film Translation',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='synopsis',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.AddField(
            model_name='movietranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='videoRental.Movie'),
        ),
        migrations.AlterUniqueTogether(
            name='movietranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
