# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoRental', '0009_auto_20181112_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='acteur'),
        ),
        migrations.AlterField(
            model_name='movierent',
            name='checkout_date',
            field=models.DateTimeField(verbose_name='date de location'),
        ),
    ]
